(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
  ;; The 'Green' part below fixes an issue where the Help Window and other child windows dobn't take the values set in '.emacs':
 '(ansi-color-names-vector ["black" "red" "green" "yellow" "pink" "magenta" "cyan" "white"])
 '(appt-message-warning-time 60 t)
 '(aquamacs-additional-fontsets nil t)
 '(aquamacs-customization-version-id 0 t)
 '(aquamacs-tool-bar-user-customization nil t)
 '(browse-url-browser-function (quote browse-url-firefox-new-tab))
 '(browse-url-generic-program "~/utils/firefox/firefox")
 '(calculator-number-digits 10)
 '(case-fold-search t)
 '(current-language-environment "Latin-1")                  
 '(default-frame-alist (quote ((tool-bar-lines . 0) (menu-bar-lines . 1) (background-color . "Gray10") (foreground-color . "Green") (left . 0) (width . 141) (height . 44))))
 '(default-input-method "latin-1-prefix")
 '(dired-recursive-deletes (quote top))
 '(display-time-mode t)
 '(font-use-system-font t)
 '(frame-background-mode nil)
 '(indent-tabs-mode nil)
 '(js2-mode-escape-quotes nil)
 '(mail-host-address "")
 '(midnight-delay 34200)
 '(midnight-hook (quote (update-my-calendar)))
 '(midnight-mode t nil (midnight))
 '(ns-tool-bar-display-mode nil t)
 '(ns-tool-bar-size-mode nil t)
 '(printer-name "USB001")
 '(smtpmail-default-smtp-server "smtp.earthlink.net")
 '(speedbar-show-unknown-files t)
 '(speedbar-use-images t)
 '(standard-indent 4)
 '(tabbar-mode nil nil (tabbar))
 '(uniquify-buffer-name-style nil nil (uniquify))
 '(user-full-name "Christopher M. Balz")
 '(visual-line-mode nil t)
 '(which-function-mode nil nil (which-func)))
